/*Punto 1:
Escribir un programa que solicite la edad y si es mayor de 18 años mostrar un mensaje que ya puede conducir, si la edad ingresada no es un número válido indicarlo en un mensaje.*/

/*let edad = prompt("Ingrese su edad")
 if (edad >= 18){
 document.write("Ya tiene permiso de conducir")}
 else if (edad < 18) {
    document.write("Número invalido")}*/

 /* Punto 2: 
 Escribir un programa que solicite una nota (número) de 0  a 10. Luego mostrar la calificación en un alert según determinados rangos 

 let nota = prompt("Ingresar su nota del 0 al 10")
if (!isNaN(nota) && nota >= 0 && nota <= 10) {
if (nota >= 0 && nota <= 2) {
        alert("Muy deficiente");
 } else if (nota >= 3 && nota <= 4) {
        alert("Insuficiente");
} else if (nota >= 5 && nota <= 6) {
        alert("Suficiente");
} else if (nota == 7) {
        alert("Bien");
} else if (nota >= 8 && nota <= 9) {
        alert("Notable");
} else if (nota ==10) {
        alert("Sobresaliente");
}
} else if (isNaN(nota)) {
    alert("Introduce un número válido");
} else {
    alert("Número erróneo");} */

/*Punto 3:
Realiza un script que pida cadenas de texto  hasta que se pulse “cancelar”. Al salir con “cancelar” deben mostrarse todas las cadenas concatenadas con un guión. */

let cadena = prompt("Ingresar texto")


